appId: foobar
filters:
  - party: "Alice"
    templates:
      - packageId: "0f766bec38fe370b7dc4ae41c28c24a8f85e3fce087c496146f414772924a172"
        moduleName: "Iou"
        entityName: "Iou"
      - packageId: "0f766bec38fe370b7dc4ae41c28c24a8f85e3fce087c496146f414772924a172"
        moduleName: "Iou"
        entityName: "IouTransfer"
messaging:
  type: "kafka"
  className: "com.tibco.dovetail.messaging.kafka.KafkaPublisher"
  properties:
    bootstrap.servers: "localhost:19092"
    clientId: "IouApp"
    Iou.Iou.created: "iou.created"
    Iou.Iou.archived: "iou.archived"
    Iou.IouTransfer.created: "ioutransfer.created"
    Iou.IouTransfer.archived: "ioutransfer.archived"
    command: command.status
  
  